### ISSUE TITLE
Crash with mutiny

### ISSUE THREAD

**Issue by jbuck** [jbuck/npm-readonly-mirror#4]
```
processing {"seq":834915,"id":"mutiny","changes":[{"rev":"15-522d232f6848b048601de9c6351132c6"}],"retry_count":0}

/home/ubuntu/npm-readonly-mirror/lib/utils.js:11
        (!sink.versions[v]) ||
                       ^
TypeError: Cannot read property '0.1.0' of undefined
    at /home/ubuntu/npm-readonly-mirror/lib/utils.js:11:24
    at Array.filter (native)
    at Object.module.exports.diff_package (/home/ubuntu/npm-readonly-mirror/lib/utils.js:9:43)
    at /home/ubuntu/npm-readonly-mirror/lib/tasks.js:93:26
    at fn (/home/ubuntu/npm-readonly-mirror/node_modules/async/lib/async.js:579:34)
    at Object._onImmediate (/home/ubuntu/npm-readonly-mirror/node_modules/async/lib/async.js:495:34)
    at processImmediate [as _immediateCallback] (timers.js:330:15)
```

The content of this package on S3 was 

```
{"error":"shutdown","reason":"{gen_server,call,[<0.20605.2709>,{pread_iolist,199312840832},infinity]}"}
```

**Comment by jbuck** [comment]
Got this with ep_page_ruler now
