### ISSUE TITLE
404 Failure on trying to install grunt-contrib-connect

### ISSUE THREAD

**Issue by k88hudson** [jbuck/npm-readonly-mirror#6]
``` bash

$ npm install grunt-contrib-compress --save-dev
npm http GET https://dccmzgc64kzf2.cloudfront.net/grunt-contrib-compress
npm http 304 https://dccmzgc64kzf2.cloudfront.net/grunt-contrib-compress
npm http GET https://dccmzgc64kzf2.cloudfront.net/registry/grunt-contrib-compress/grunt-contrib-compress-0.6.1.tgz
npm http 404 https://dccmzgc64kzf2.cloudfront.net/registry/grunt-contrib-compress/grunt-contrib-compress-0.6.1.tgz
npm ERR! fetch failed https://dccmzgc64kzf2.cloudfront.net/registry/grunt-contrib-compress/grunt-contrib-compress-0.6.1.tgz
npm ERR! Error: 404 Not Found
npm ERR!     at WriteStream.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/fetch.js:57:12)
npm ERR!     at WriteStream.EventEmitter.emit (events.js:117:20)
npm ERR!     at fs.js:1596:14
npm ERR!     at /usr/local/lib/node_modules/npm/node_modules/graceful-fs/graceful-fs.js:103:5
npm ERR!     at Object.oncomplete (fs.js:107:15)
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Darwin 13.0.0
npm ERR! command "/usr/local/bin/node" "/usr/local/bin/npm" "install" "grunt-contrib-compress" "--save-dev"
npm ERR! cwd /Users/k88hudson/github/webmaker-auth-client
npm ERR! node -v v0.10.22
npm ERR! npm -v 1.3.14
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /Users/k88hudson/github/webmaker-auth-client/npm-debug.log
npm ERR! not ok code 0
```

**Comment by jbuck** [comment]
Fixing now

**Comment by jbuck** [comment]
All fixed!
